name: Daily Build

on:
  schedule:
    - cron: '0 8 * * *' # Runs daily at 08:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  run_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run Go program
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: go run ./main.go

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Automated changes by 'daily build' GitHub Action"
            git push origin main
          else
            echo "No changes to commit."
          fi
